# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSReactTest1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTest1
  pod 'MobileCenter/Push', '~> 0.10.1'
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.6.0'

  

  target 'iOSReactTest1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSReactTest1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTest1-tvOS

  target 'iOSReactTest1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
